-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."HOUR" AS ENUM('"07:00"', '"07:50"', '"08:00"', '"08:50"', '"09:00"', '"09:50"', '"10:00"', '"10:50"', '"11:00"', '"11:50"', '"12:00"', '"12:50"', '"13:30"', '"14:20"', '"14:30"', '"15:20"', '"15:30"', '"16:20"', '"16:30"', '"17:20"', '"17:30"', '"18:20"', '"18:30"', '"19:20"', '"19:30"', '"20:20"');--> statement-breakpoint
CREATE TYPE "public"."SEMESTER" AS ENUM('GASAL', 'GENAP');--> statement-breakpoint
CREATE TYPE "public"."USER_TYPE" AS ENUM('STUDENT', 'LECTURER');--> statement-breakpoint
CREATE TYPE "public"."WEEKDAY" AS ENUM('SENIN', 'SELASA', 'RABU', 'KAMIS', 'JUMAT');--> statement-breakpoint
CREATE TABLE "schedule_list" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schedule_list_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"semester" "SEMESTER" NOT NULL,
	"year" text NOT NULL,
	"user_id" uuid NOT NULL
);
--> statement-breakpoint
ALTER TABLE "schedule_list" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "course" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "course_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"code" text,
	"name" text,
	"sks" smallint,
	"description" text
);
--> statement-breakpoint
ALTER TABLE "course" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "rooms" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rooms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text,
	"capacity" integer
);
--> statement-breakpoint
ALTER TABLE "rooms" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "schedule" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schedule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"course_id" bigint,
	"room_id" bigint,
	"lecturer_id" bigint,
	"week_day" "WEEKDAY",
	"start_hour" "HOUR",
	"end_hour" "HOUR",
	"schedule_list_id" bigint
);
--> statement-breakpoint
ALTER TABLE "schedule" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "lecturer" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lecturer_ids_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"nip" text,
	"name" text,
	"faculty" text,
	"expertise" text
);
--> statement-breakpoint
ALTER TABLE "lecturer" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "schedule_list" ADD CONSTRAINT "schedule_list_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "schedule" ADD CONSTRAINT "schedule_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."course"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "schedule" ADD CONSTRAINT "schedule_lecturer_id_fkey" FOREIGN KEY ("lecturer_id") REFERENCES "public"."lecturer"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "schedule" ADD CONSTRAINT "schedule_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "schedule" ADD CONSTRAINT "schedule_schedule_list_id_fkey" FOREIGN KEY ("schedule_list_id") REFERENCES "public"."schedule_list"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
CREATE POLICY "Policy with table joins" ON "course" AS PERMISSIVE FOR UPDATE TO "supabase_admin" USING (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "course" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "course" AS PERMISSIVE FOR INSERT TO "supabase_admin";--> statement-breakpoint
CREATE POLICY "Enable delete for users based on user_id" ON "course" AS PERMISSIVE FOR DELETE TO "supabase_admin";--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "rooms" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "rooms" AS PERMISSIVE FOR INSERT TO "supabase_admin";--> statement-breakpoint
CREATE POLICY "Enable delete for users based on user_id" ON "rooms" AS PERMISSIVE FOR DELETE TO "supabase_admin";--> statement-breakpoint
CREATE POLICY "Enable update for users based on user_id" ON "rooms" AS PERMISSIVE FOR UPDATE TO "supabase_admin";--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "lecturer" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "lecturer" AS PERMISSIVE FOR INSERT TO "supabase_admin";--> statement-breakpoint
CREATE POLICY "Enable delete for users based on user_id" ON "lecturer" AS PERMISSIVE FOR DELETE TO "supabase_admin";--> statement-breakpoint
CREATE POLICY "Policy with table joins" ON "lecturer" AS PERMISSIVE FOR UPDATE TO "supabase_admin";
*/